### ISSUE TITLE
Control over optimization variables

### ISSUE THREAD

**Issue by votroto** [jump-dev/SumOfSquares.jl#208]
The variables of a polynomial might be different both from the effective variables of the polynomial, as well as from the variables of the optimization domain.

Let `d = @set y^2 <= 1` be the optimization domain, and fix a dynamic polynomial `p = subs(x + y, x=>1)`. The `effective_variables` of `p` are `[y]`; while its `variables` are `[x, y]` ([see DynamicPolynomials issue](https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/92)); and the `variables` of `d` are `[y]`.

Now, optimizing `p` over `d`, SumOfSquares tries to optimize over `[x, y]` i.e. its `variables`.

```julia
model = SOSModel(Mosek.Optimizer)
@variable model a
@objective model Max a
@constraint(model, c, p - a >= 0, domain=d)
optimize!(model)

objective = objective_value(model)
atoms = extractatoms(moment_matrix(c), 1e-4)
```

Switching to `effective_variables` might still break POLA, when p "loses" some of its variables. Consider optimizing over parametrized polynomials in the form `C*x+y` for `C in 0:10` over `@set y^2 <= 1 && x^2 <= 1`. Would this work as expected?

I suggest SumOfSquares use the variables of the optimization domain instead, as those are likely intentional (Especially given the "user-friendly-ness" of the current API of SemialgebraicSets.jl).

**Comment by blegat** [comment]
> I suggest SumOfSquares use the variables of the optimization domain instead

What about `@constraint(model, x^2 + y^2, domain = @set x <= 1)` ?

> Switching to `effective_variables` might still break POLA, when p "loses" some of its variables. Consider optimizing over parametrized polynomials in the form `C*x+y` for `C in 0:10` over `@set y^2 <= 1 && x^2 <= 1`. Would this work as expected?

That wouldn't be an issue. With `C = 0`, that would first be reformulated into `y - s1 * (1 - y^2) - s2 * (1 - x^2)` and we then take the effective variables of that polynomial which is `[x, y]`

**Comment by votroto** [comment]
Sorry for late reply, I'm assuming the costraint `x^2 + y^2` is missing a `>= 0`, right?
I did not know you could specify such a domain. So if you forget to specify a domain for a variable, there is an implicit `∀y ∈ R` put there for you? Interesting.

What I was worried about was this (issue in comments, for ease of copy-paste):
```julia
using MultivariatePolynomials
using DynamicPolynomials
using SemialgebraicSets
using SumOfSquares
using CSDP
using JuMP

# Given an optimization routine such as:

function find_min(p::AbstractPolynomial, d::AbstractSemialgebraicSet)
	model = SOSModel(CSDP.Optimizer)
	@variable model a
	@objective model Max a
	@constraint(model, c, p - a >= 0, domain=d, maxdegree=4)

	set_silent(model)
	optimize!(model)

	objective = objective_value(model)
	measure = extractatoms(moment_matrix(c), 1e-4)

	objective, measure
end

# and

@polyvar x y C
domain = @set y^2 <= 1 && x^2 <= 1

# -----------------------------------------------------------------------------
# contrast the behavior of:
# -----------------------------------------------------------------------------
@show find_min(subs(C*x + y, C=>-1), domain)
@show find_min(subs(C*x + y, C=>0), domain)
@show find_min(subs(C*x + y, C=>1), domain)

# which returns nothing

# -----------------------------------------------------------------------------
# with the "equivalent" but manual
# -----------------------------------------------------------------------------
@show find_min(-x + y, domain)
@show find_min(y, domain)
@show find_min(x + y, domain)

# which returns atomic measures
```
The first case assumes I want to optimize over `C`s as well (which I do not. I used `subs` to make it a constant).

Is there a way to say "consider a polynomial `p(x,y,C)` as a polynomial only in variables `x,y`"?

Thanks

**Comment by blegat** [comment]
> Sorry for late reply, I'm assuming the costraint `x^2 + y^2` is missing a `>= 0`, right?

Yes, I fixed it.
> I did not know you could specify such a domain. So if you forget to specify a domain for a variable, there is an implicit `∀y ∈ R` put there for you? Interesting.

Yes, the other variables are assumed to be free if there is not constraint on them.

> The first case assumes I want to optimize over `C`s as well (which I do not. I used `subs` to make it a constant).
> 
> Is there a way to say "consider a polynomial `p(x,y,C)` as a polynomial only in variables `x,y`"?

You could add `C == 1` in the domain but substituting should work if you use `effective_variables` since `effective_variables(subs(C*x + y, C=>-1))` is `[x, y]`.

**Comment by votroto** [comment]
Oh, if there are optimization variables missing from the polynomial, it's as if they have zero coefficients; and if there are polynomial variables missing from the domain, they are assumed free.

Yeah, this is great. Ok, I'm convinced `effective_variables` is the right solution.

Thanks for your help

_BTW I think adding explicit substitutions to the domain would be far too tedious._

**Comment by blegat** [comment]
> BTW I think adding explicit substitutions to the domain would be far too tedious.

Note that when you have `x == 1` inside the `@set` macro, it is detected as a variable substitution and handled more efficiently:
https://github.com/JuliaAlgebra/SemialgebraicSets.jl/blob/e55a5f3cf623e95c30c7d31d77501c88270199fb/src/fix.jl
The advantage is that in SumOfSquares, we just substitute `c` for `1`. We might still use `C` in `s1` and `s2` of `C*x + y - s1 * (1 - y^2) - s2 * (1 - x^2)` though.

**Comment by votroto** [comment]
The [DynamicPolynomials update](https://github.com/JuliaAlgebra/DynamicPolynomials.jl/pull/95#issue-1014080076) fixes all of my issues. Substitutions now interact with SumOfSquares as expected.
Thank you :)
