### ISSUE TITLE
Formulating trigonometric functions within SOS

### ISSUE THREAD

**Issue by jediofgever** [jump-dev/SumOfSquares.jl#252]
Hi, 
I am trying to obtain a candidate Lyapunov function for a dynamical system.
However in the state dynamics I have trigonometric functions such as sin and cos.
I wonder whether it is possible to handle this cases while formulating SOS,
I cant see an example of such case and will highly appreciate if you could help. 
Thank you.

**Comment by blegat** [comment]
It is sometimes possible by doing the change of variables `sin(a) = x`, `cos(a) = y` and adding `x^2 + y^2 == 1` in the domain.

**Comment by jediofgever** [comment]
Thank you @blegat
