### ISSUE TITLE
Rendering the underscore in the online documentation

### ISSUE THREAD

**Issue by hurak** [jump-dev/SumOfSquares.jl#256]
In [the documentation in the section with an example on Lyapunov function search](https://jump.dev/SumOfSquares.jl/latest/generated/Systems%20and%20Control/lyapunov_function_search/) (but perhaps also elsewhere) I encountered a possibly confusing LaTeX-based math rendering. Namely, when an underscore is followed by a left square bracket: `_[`. For example, right after the code

```julia
@variable(model, V, Poly(monos))
```
Obviosly the underlying LaTeX rendering engine interprets the underscore preceeding the left square bracket as a command to render the bracket as a lower index.

**Comment by blegat** [comment]
Thanks for letting us know about this issue. It was broken by https://github.com/jump-dev/JuMP.jl/pull/2822

**Comment by blegat** [comment]
Should be fixed by https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/223
