### ISSUE TITLE
Primal residual computation

### ISSUE THREAD

**Issue by htadashi** [jump-dev/SumOfSquares.jl#327]
Hi @blegat, is there (or any plans to add) a function in SumOfSquares.jl that checks the difference between the SOS decomposition found by the solver and the original polynomial (similar to YALMIP's [checkset](https://yalmip.github.io/tutorial/sumofsquaresprogramming/#:~:text=The%20quality%20of%20the,v(x)) command)?

**Comment by blegat** [comment]
If `con_ref` is the constraint reference and `p` is the polynomial you can get the difference with `sos_decomposition(con_ref) - p`

**Comment by htadashi** [comment]
Thanks for clarifying! :)
