### ISSUE TITLE
Broken link to motzkin notebook on the web page

### ISSUE THREAD

**Issue by hurak** [jump-dev/SumOfSquares.jl#338]
The last sentence of the section [When is nonnegativity equivalent to sum of squares ?](https://jump.dev/SumOfSquares.jl/dev/sumofsquares/#When-is-nonnegativity-equivalent-to-sum-of-squares-?) contains a reference to [motzkin notebook](https://github.com/jump-dev/SumOfSquares.jl/blob/master/examples/motzkin.ipynb), but the link is broken. There is no such file in the [https://github.com/jump-dev/SumOfSquares.jl/tree/master/examples](https://github.com/jump-dev/SumOfSquares.jl/tree/master/examples) directory.

**Comment by blegat** [comment]
Thanks for reporting this!
